apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  selector:
    app: evaluation
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP