apiVersion: batch/v1
kind: Job
metadata:
  name: evaluation-job
spec:
  template:
    spec:
      containers:
      - name: evaluation-container
        image: haris001/hdb-evaluate:v73.0
        imagePullPolicy: Always
        volumeMounts:
        - name: evaluation-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: evaluation-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Never
  backoffLimit: 3
