apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api-container
        image: hhym123/flask:v18.0
        imagePullPolicy: Always
        volumeMounts:
        - name: flask-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
        ports:                      
        - containerPort: 5000
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: pvc
