apiVersion: v1
kind: Service
metadata:
  name: flask-api-service-cluster
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # External access for the web interface