apiVersion: v1
kind: Service
metadata:
  name: flask-api-service-node
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort  # External access for the web interface