apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP