apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
      - name: prediction-container
        image: hhym123/predict:v5.0
        imagePullPolicy: Always
        volumeMounts:
        - name: prediction-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 8003
      volumes:
      - name: prediction-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Always
