apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
spec:
  selector:
    app: preprocessing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Internal service only