apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
      - name: preprocessing-container
        image: hhym123/preprocessing:v5.0
        imagePullPolicy: Always
        volumeMounts:
        - name: preprocessing-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 8000
      volumes:
      - name: preprocessing-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Always
