apiVersion: batch/v1
kind: Job
metadata:
  name: preprocessing-job
spec:
  template:
    spec:
      containers:
      - name: preprocessing-container
        image: cjunzhao/hdb-preprocessing:v75.0
        imagePullPolicy: Always
        volumeMounts:
        - name: preprocessing-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: preprocessing-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Never
  backoffLimit: 3
