apiVersion: v1
kind: Pod
metadata:
  name: preprocessing-pod
spec:
  containers:
  - name: preprocessing-container
    image: hhym123/hdb-preprocessing:v73.0
    imagePullPolicy: Always
    volumeMounts:
      - name: preprocessing-storage
        mountPath: /app/data  # Saves preprocessed data here
  volumes:
    - name: preprocessing-storage
      persistentVolumeClaim:
        claimName: pvc
  restartPolicy: Never
