apiVersion: v1
kind: Pod
metadata:
  name: preprocessing-pod
spec:
  containers:
  - name: preprocessing-container
    image: cjunzhao/hdb-preprocessing:latest
    volumeMounts:
      - name: preprocessing-storage
        mountPath: /app/data  # Saves preprocessed data here
  volumes:
    - name: preprocessing-storage
      persistentVolumeClaim:
        claimName: pvc
  restartPolicy: Never
