apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: hhym123/hdb-training:v75.0
        imagePullPolicy: Always
        volumeMounts:
        - name: training-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: training-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Never
  backoffLimit: 3
