apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training-container
        image: walkingduck/training
        imagePullPolicy: Always
        volumeMounts:
        - name: training-storage
          mountPath: /app/data
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 8000
      volumes:
      - name: training-storage
        persistentVolumeClaim:
          claimName: pvc
      restartPolicy: Always